# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6ad9d4fad30bcfda3481550e1f91c6503ea19e48bef2276102ba081fa9fc00cfc2a7b926307a08ae98b85fdba9f09aff029a72d3ea4546c3ae2f79448be1bbf

test:
  secret_key_base: 99851a74764bbdd54c7c39ec620b012d5a9d67958694ef8ed1078c57468448402a97bcaacad0e42c141a36f2449556d025f65f408e7309b19c136712bf9a735f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
